"""add budgets table

Revision ID: 369ed57629d5
Revises: 202605220001
Create Date: 2026-05-22 04:03:18.918633
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '369ed57629d5'
down_revision = '202605220001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_index(op.f('ix_budgets_budget_id'), 'budgets', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budgets_category'), 'budgets', ['category'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_budget_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
