"""add insight history

Revision ID: a14e750cac51
Revises: daf63f754471
Create Date: 2026-06-09 16:07:16.848459
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a14e750cac51'
down_revision = 'daf63f754471'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_history',
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('priority_level', sa.String(length=50), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.import_batch_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_index(op.f('ix_insight_history_import_batch_id'), 'insight_history', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_insight_history_insight_id'), 'insight_history', ['insight_id'], unique=False)
    op.create_index(op.f('ix_insight_history_user_id'), 'insight_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insight_history_user_id'), table_name='insight_history')
    op.drop_index(op.f('ix_insight_history_insight_id'), table_name='insight_history')
    op.drop_index(op.f('ix_insight_history_import_batch_id'), table_name='insight_history')
    op.drop_table('insight_history')
    # ### end Alembic commands ###
