"""add csv import batches

Revision ID: daf63f754471
Revises: 369ed57629d5
Create Date: 2026-05-23 22:48:29.219374
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'daf63f754471'
down_revision = '369ed57629d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('import_batch_id')
    )
    op.create_index(op.f('ix_import_batches_import_batch_id'), 'import_batches', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_import_batches_user_id'), 'import_batches', ['user_id'], unique=False)
    op.add_column(
        'transactions',
        sa.Column('source', sa.String(length=30), nullable=False, server_default='manual'),
    )
    op.add_column('transactions', sa.Column('import_batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_import_batch_id'), 'transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_source'), 'transactions', ['source'], unique=False)
    op.create_foreign_key(
        'fk_transactions_import_batch_id_import_batches',
        'transactions',
        'import_batches',
        ['import_batch_id'],
        ['import_batch_id'],
    )
    op.alter_column('transactions', 'source', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_transactions_import_batch_id_import_batches',
        'transactions',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_transactions_source'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_batch_id'), table_name='transactions')
    op.drop_column('transactions', 'import_batch_id')
    op.drop_column('transactions', 'source')
    op.drop_index(op.f('ix_import_batches_user_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_import_batch_id'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
